sudo: false

language: python

matrix:
  include:
    - python: '2.7'
    - python: '3.6'
    - python: '3.6'
      env: PEP8=1

install:
  - pip install --user -r requirements.txt
  - |
    # Check if this is the PEP8 test instance and install pycodestyle
    if ! [ -z "$PEP8" ]; then
       pip install --user pycodestyle
    fi

script:
  - |
    # Check if this is the PEP8 test instance and run pep8
    if [ -z "$PEP8" ]; then
      # TODO: sort out dependencies so I can just run py.test
      python -m pytest
    else
      pycodestyle ./
    fi
